version: "3.9"
services:
  app:
    build: ./infra/php
    ports:
      - 5173:5173
    volumes:
      - ./src:/data
  web:
    image: nginx:1.20-alpine
    ports:
      - 4040:80
    volumes:
      - ./src:/data
      - ./infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
    working_dir: /data
  db:
    build: ./infra/mysql
    ports:
      - 4001:3306
    volumes:
      - db-store:/var/lib/mysql
  mail:
    image: axllent/mailpit:v1.8
    container_name: mailpit
    ports:
      - 8025:8025
      - 1025:1025

volumes:
  db-store:
